name: Bug report
description: Report a reproducible issue in the live product or public docs
title: "[Bug] "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting. Please provide reproducible details.
  - type: input
    id: area
    attributes:
      label: Area
      description: Where did this happen? (home/create/gallery/pricing/dashboard/docs)
      placeholder: create
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Reproduction steps
      description: Provide exact steps
      placeholder: |
        1. Go to ...
        2. Click ...
        3. See error ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      description: Browser/OS/device
      placeholder: Chrome 123 / macOS / Desktop
